name: untitled2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  geolocator: ^8.0.5
  audioplayers: ^0.20.1

flutter_icons:
  android: true
  ios: true
  image_path: "Images/img9.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - sound/adhan.mp3
    - sound/adhan1.mp3
    - sound/adhan2.mp3
    - sound/Fajr.mp3
    - Images/img0.png
    - Images/img1.png
    - Images/img2.png
    - Images/img4.jpg
    - Images/img5.jpg
    - Images/img6.jpg
    - Images/img7.jpg
    - Images/img9.png
    - Images/img12.jpg
    - Images/img25.jpg
    - Images/img26.jpg
    - Images/img29.jpg
    - Images/img32.jpg
    - Images/fajr2.jpg
    - Images/asr1.jpg
    - Images/maghrib1.jpg
    - Images/isha2.jpg

  fonts:
    - family: BungeeShade
      fonts:
        - asset: fonts/BungeeShade-Regular.ttf
    - family: ArefRuqaa
      fonts:
        - asset: fonts/ArefRuqaa-Bold.ttf
        - asset: fonts/ArefRuqaa-Regular.ttf
    - family: font2
      fonts:
        - asset: fonts/Arabic/font2.ttf
    - family: font4
      fonts:
        - asset: fonts/Arabic/font4.ttf
    - family: font6
      fonts:
        - asset: fonts/Arabic/font6.ttf

